### ISSUE TITLE
Pls add SPX-CG to the graphics section

### ISSUE THREAD

**Issue by wde** [florisporro/awesome-ndi#5]
Hi there,

I've been using this software for over a year and it has allowed us to create and integrate CG into our broadcasts at no cost.

https://github.com/TuomoKu/SPX-GC and https://www.smartpx.fi/

Cheers,
Sean

**Comment by florisporro** [comment]
Hi Sean,

That looks awesome and I'm a fan already. However, as far as NDI goes, this does not seem to have any form of actual rendering built into it, rather it seems to rely on external applications to do the rendering to NDI much like other HTML-based graphics tools like Holographics and Singular, which I've also not included on this list for the same reason.

This would be better suited for the more general awesome-broadcast list: https://github.com/ebu/awesome-broadcasting
